all:
  hosts:
    controller-0:
      ansible_host: 172.20.1.0
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/controller-0/virtualbox/private_key
    controller-1:
      ansible_host: 172.20.1.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/controller-1/virtualbox/private_key
    controller-2:
      ansible_host: 172.20.1.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/controller-2/virtualbox/private_key
    worker-0:
      ansible_host: 172.20.2.0
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/worker-0/virtualbox/private_key
    worker-1:
      ansible_host: 172.20.2.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/worker-1/virtualbox/private_key
    worker-2:
      ansible_host: 172.20.2.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/worker-2/virtualbox/private_key
    lb-api:
      ansible_host: 172.20.0.0
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/lb-api/virtualbox/private_key
    metallb-0:
      ansible_host: 172.20.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/metallb-0/virtualbox/private_key
    metallb-1:
      ansible_host: 172.20.0.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/metallb-1/virtualbox/private_key

  children:
    etcd:
      hosts:
        controller-0:
        controller-1:
        controller-2:
    controller:
      hosts:
        controller-0:
        controller-1:
        controller-2:
    worker:
      hosts:
        worker-0:
        worker-1:
        worker-2:
    lb_api:
      hosts:
        lb-api:
    metallb:
      hosts:
        metallb-0:
        metallb-1:
