- name: Generate certificates
  hosts: deployer
  roles:
    - certificates

- name: Generate authentication configs
  hosts: deployer
  roles:
    - auth_configs

- name: Generate encryption config
  hosts: deployer
  roles:
    - encryption_config

- name: Set up Kubernetes API load balancer
  hosts: lb-api
  roles:
    - api_load_balancer
