deployer:
  certificate:
    directory: '{{ playbook_dir }}/certificates'
  auth_config:
    directory: '{{ playbook_dir }}/auth_configs'
  encryption_config:
    directory: '{{ playbook_dir }}/encryption_config'

certificate:
  ca:
    config:
      expiry: 8760h # 1 year
    attributes:
      CN: Kubernetes
      C: Russia
      L: Saint-Petersburg
      O: Home
      OU: HomeLab
      ST: Saint-Petersburg

cluster:
  name: the-hard-way
  etcd:
    version: 3.4.23
  kubernetes:
    version: 1.26.0
