deployer:
  tools:
    cfssl:
      version: 1.6.2
    cfssljson:
      version: 1.6.2
    kubectl:
      version: 1.26.0
  certificate:
    directory: /home/vagrant/kubernetes/certificates
  auth_config:
    directory: /home/vagrant/kubernetes/auth_configs

certificate:
  ca:
    config:
      expiry: 8760h
    attributes:
      CN: Kubernetes
      C: Russia
      L: Saint-Petersburg
      O: Home
      OU: HomeLab
      ST: Saint-Petersburg

cluster:
  name: the-hard-way
