- import_tasks: requirements.yml

- name: Prepare certificate directories
  file:
    path: '{{ item.path }}'
    state: directory
  with_items:
    - path: '{{ deployer.certificate.directory }}/configs'
    - path: '{{ deployer.certificate.directory }}/ca'
    - path: '{{ deployer.certificate.directory }}/admin'
    - path: '{{ deployer.certificate.directory }}/worker'
    - path: '{{ deployer.certificate.directory }}/kube-controller-manager'
    - path: '{{ deployer.certificate.directory }}/kube-proxy'
    - path: '{{ deployer.certificate.directory }}/kube-scheduler'
    - path: '{{ deployer.certificate.directory }}/kubernetes'
    - path: '{{ deployer.certificate.directory }}/service-account'

- name: Render certificate configs
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: ca-config.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/ca-config.json'
    - src: ca-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/ca-csr.json'
    - src: admin-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/admin-csr.json'
    - src: kube-controller-manager-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/kube-controller-manager-csr.json'
    - src: kube-proxy-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/kube-proxy-csr.json'
    - src: kube-scheduler-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/kube-scheduler-csr.json'
    - src: kubernetes-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/kubernetes-csr.json'
    - src: service-account-csr.json.j2
      dest: '{{ deployer.certificate.directory }}/configs/service-account-csr.json'

- name: Generate root CA
  shell:
    cmd: |
      cfssl gencert -initca \
        {{ deployer.certificate.directory }}/configs/ca-csr.json \
        | cfssljson -bare ca
    chdir: "{{ deployer.certificate.directory }}/ca"

- name: Generate admin client certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/admin-csr.json \
        | cfssljson -bare admin
    chdir: "{{ deployer.certificate.directory }}/admin"

- name: Render worker certificate configs
  template:
    src: worker-csr.json.j2
    dest: '{{ deployer.certificate.directory }}/configs/{{ item }}-csr.json'
  with_items: '{{ groups["worker"] }}'

- name: Generate worker certificates
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        -hostname={{ item }},{{ hostvars[item]['ansible_host'] }} \
        {{ deployer.certificate.directory }}/configs/{{ item }}-csr.json \
        | cfssljson -bare {{ item }}
    chdir: "{{ deployer.certificate.directory }}/worker"
  with_items: '{{ groups["worker"] }}'

- name: Generate controller manager certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/kube-controller-manager-csr.json \
        | cfssljson -bare kube-controller-manager
    chdir: "{{ deployer.certificate.directory }}/kube-controller-manager"

- name: Generate kube-proxy certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/kube-proxy-csr.json \
        | cfssljson -bare kube-proxy
    chdir: "{{ deployer.certificate.directory }}/kube-proxy"

- name: Generate scheduler certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/kube-scheduler-csr.json \
        | cfssljson -bare kube-scheduler
    chdir: "{{ deployer.certificate.directory }}/kube-scheduler"

- name: Generate API server certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/kubernetes.json \
        | cfssljson -bare kubernetes
    chdir: "{{ deployer.certificate.directory }}/kubernetes"

- name: Generate service account certificate
  shell:
    cmd: |
      cfssl gencert \
        -ca={{ deployer.certificate.directory }}/ca/ca.pem \
        -ca-key={{ deployer.certificate.directory }}/ca/ca-key.pem \
        -config={{ deployer.certificate.directory }}/configs/ca-config.json \
        -profile=kubernetes \
        {{ deployer.certificate.directory }}/configs/service-account-csr.json \
        | cfssljson -bare kubernetes
    chdir: "{{ deployer.certificate.directory }}/service-account"