- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: Generate config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
